version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: ./scripts/BeforeInstall.sh
      runas: root
  AfterInstall:
    - location: ./scripts/AfterInstall.sh
      runas: root
  ApplicationStop:
    - location: ./scripts/ApplicationStop.sh
      runas: root
  ApplicationStart:
    - location: ./scripts/ApplicationStart.sh
      runas: root
